const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
const ORDER_PROCESS = 'ORDER_PROCESS';
const WELCOME = 'WELCOME';
const USER_BANNED = 'USER_BANNED';
const LOGOUT = 'LOGOUT';

export {
    FORGOT_PASSWORD,
    ORDER_PROCESS,
    WELCOME,
    USER_BANNED,
    LOGOUT,
};