module.exports = {
    authRouter: require('./auth.router'),
    userRouter: require('./user.router'),
    managerRouter: require('./manager.router'),
    institutionRouter: require('./institution.router'),
    ratingRouter: require('./rating.router'),
    newsRouter: require('./news.router'),
    reviewRouter: require('./review.router'),
    commentRouter: require('./comment.router'),
    cityRouter: require('./city.router'),
    menuRouter: require('./menu.router'),
    messageRouter: require('./message.router'),
    conversationRouter: require('./conversation.router'),
    caplRouter: require('./capl.router'),
}