module.exports = {
    userController: require('./user.controller'),
    managerController: require('./manager.controller'),
    authController: require('./auth.controller'),
    institutionController: require('./institution.controller'),
    ratingController: require('./rating.controller'),
    newsController: require('./news.controller'),
    reviewController: require('./review.controller'),
    commentController: require('./comment.controller'),
    cityController: require('./city.controller'),
    menuController: require('./menu.controller'),
    messageController: require('./message.controller'),
    conversationController: require('./conversation.controller'),
    caplController: require('./capl.controller'),
}