module.exports = {
    emailService: require('./email.service'),
    s3Service: require('./s3.service'),
    cloudService: require('./cloud.service'),
    smsService: require('./sms.service'),
    userService: require('./user.service'),
    managerService: require('./manager.service'),
    passwordService: require('./password.service'),
    institutionService: require('./institution.service'),
    ratingService: require('./rating.service'),
    newsService: require('./news.service'),
    reviewService: require('./review.service'),
    commentService: require('./comment.service'),
    messageService: require('./message.service'),
    conversationService: require('./conversation.service'),
    caplService: require('./capl.servise'),
    scheduler: require('./scheduler'),
    reserve: require('./isActiveReserve'),
}